# This is a basic workflow to help you get started with Actions

name: Editor

# Controls when the workflow will run
on: 
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      branch: 'main'
      source_base_url: "https://raw.githubusercontent.com/${{ github.repository }}/main/"
      web_editor_url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
    steps:
      - name: Checkout ${{ env.branch }} branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.branch }}

#      - name: update version branches
#        uses: leanprover-contrib/update-versions-action@master

      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          echo "short_lean_version=$(~/.elan/bin/lean --run scripts/lean_version.lean)" >> $GITHUB_ENV

      - name: install Python
        if: ${{ ! 0 }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install mathlibtools
        run: python -m pip install --upgrade pip mathlibtools

      - name: leanpkg configure
        run: leanpkg configure

      - name: get mathlib cache
        run: leanproject get-mathlib-cache || true
        
      - name: leanpkg build
        id: build
        run: |
          lean --make src || true

    ## Now we generate the editor ##

      - name: Install lean editor
        run: git clone --depth=1 https://github.com/leanprover-community/lean-web-editor.git

      - name : Get server files
        run: |
          mkdir -p dist
          VER=`lean -v |sed -nE 's/.*version ([0-9]+\.[0-9]+\.[0-9]+).*/\1/pi'`
          wget -q https://github.com/leanprover-community/lean/releases/download/v$VER/lean-$VER--browser.zip
          unzip *.zip
          mv build/shell/* dist/

      - name: generate library.zip
        run: ./generate_library.sh

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: library
          path: |
            ./dist/library.zip
            ./dist/library.*.json

      - name: build
        run: |
          mv dist lean-web-editor/
          cd lean-web-editor
          npm install
          NODE_ENV=production ./node_modules/.bin/webpack
  
      - name: place editor in the website
        run: mv lean-web-editor/dist html/
    
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.github_token }}
          branch: gh-pages # The branch the action should deploy to.
          folder: ./html # The folder the action should deploy.
          single-commit: "true"
          clean: "false"
